# Generated by Django 5.2.4 on 2025-08-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.CharField(max_length=400)),
            ],
        ),
    ]
